### ISSUE TITLE
datetime as first class type

### ISSUE THREAD

**Issue by tshepang** [m-cat/over#2]
Would be nice... I appreciate it in toml

**Comment by m-cat** [comment]
Just saw this, am not getting GitHub notifications for some reason.

I briefly considered this but think it would add far too much complexity, particularly as different locales have different date formats. It is better for the consuming application to define a format which can then be a simple string in the over file. Sorry if this is not the answer you were expecting, but surely we can improve on the abominations that are TOML and YAML.
