### ISSUE TITLE
Name OVER is difficult to google / conflicts with a lot of other things

### ISSUE THREAD

**Issue by nmrshll** [m-cat/over#3]
Great config format ! Thanks for that. 

One small issue I had was trying to find it again, even when I knew it was called OVER it is difficult to find with a google search, because the word "over" stands for so many things.

Maybe at some point in the future it would be useful to rename it if it's ever going to be widely accepted (and I hope so).

**Comment by nmrshll** [comment]
Oh...

I did mean that as a serious issue.  People are going to google for "how to do X with over", and it's going to return a lot of unrelated results.

**Comment by m-cat** [comment]
I guess I'm sympathetic to that, but I simply have no intention of changing the name.

**Comment by nmrshll** [comment]
That's all right for me, just wanted to make sure you were aware.

**Comment by m-cat** [comment]
Thanks 🙂
